// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpkcivtcmiyanmpeceqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwa2NpdnRjbWl5YW5tcGVjZXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDMwODgsImV4cCI6MjA2MjYxOTA4OH0.oH7IKyiOXn6osIvlwLbJ2fgU76nC9c0XvQ0NWgHQUHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);